# -*- coding: utf-8 -*-
"""TCC_Reformulado.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eiW-sURYotMfGaGIhdPAHbRT5hxNCu0V

# Inicialização do ambiente
"""

import signal
import sys

def signal_handler(sig, frame):
    print("Exiting gracefully...")
    sys.exit(0)

signal.signal(signal.SIGINT, signal_handler)


# Standard library imports
import random
from typing import List, Dict, Union

# Third-party library imports
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import torch

# Scikit-learn imports
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.experimental import enable_iterative_imputer  # Required for IterativeImputer
from sklearn.impute import SimpleImputer, IterativeImputer, KNNImputer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    cross_validate,
    KFold,
    StratifiedKFold,
    GridSearchCV,
)
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.feature_selection import (
    SelectKBest,
    SelectPercentile,
    RFE,
    RFECV,
)
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier


# External library imports
from pmlb import fetch_data

# Local imports
from utils import *

# Visualization imports
from matplotlib.axes._axes import Axes


#"LR",
target_algorithms = ["NN"]#,"KNN", "SVC", "LR", "NB","DT", "RF"]

sub_ds_list = ["GAMETES_Epistasis_2_Way_1000atts_0.4H_EDM_1_EDM_1_1","agaricus_lepiota","mushroom","ring","twonorm"]
partial_ds = ["waveform_40","waveform_21","movement_libras","satimage","chess","kr_vs_kp","optdigits","splice","texture","sonar","molecular_biology_promoters","mfeat_fourier","analcatdata_authorship","tokyo1","soybean","mfeat_karhunen"]
ds_list = ["GAMETES_Epistasis_2_Way_1000atts_0.4H_EDM_1_EDM_1_1","agaricus_lepiota","mushroom","ring","twonorm","clean1","dna","phoneme","mfeat_pixel","banana","mfeat_factors","spambase","Hill_Valley_with_noise","Hill_Valley_without_noise","waveform_40","waveform_21","movement_libras","satimage","chess","kr_vs_kp","optdigits","splice","texture","sonar","molecular_biology_promoters","mfeat_fourier","analcatdata_authorship","tokyo1","soybean","mfeat_karhunen"]

new_list = ["satimage","chess","kr_vs_kp","optdigits","splice","texture","sonar","molecular_biology_promoters","mfeat_fourier","analcatdata_authorship","tokyo1","soybean","mfeat_karhunen"]
#ds_list = new_list
NUM_TRIALS = 6

def get_estimator(alg):
  if alg == "KNN":
    return KNeighborsClassifier()
  elif alg == "SVC":
    return SVC(kernel="linear", C=1, random_state = 42,max_iter=500000)
  elif alg == "LR":
    return LogisticRegression(random_state=42,max_iter=5000,solver="sag")
  elif alg == "NB":
    return GaussianNB()
  elif alg == "DT":
    return DecisionTreeClassifier(random_state=42)
  elif alg == "NN":
    return MLPClassifier(hidden_layer_sizes=(100,), max_iter=500, random_state=42)
  else:
    return RandomForestClassifier(random_state=42)

def get_scoring(n_classes):
  if n_classes > 2:
    scoring = ['accuracy', 'balanced_accuracy','f1_macro','precision_macro','recall_macro']
  else:
    scoring = ['accuracy', 'balanced_accuracy','f1','precision','recall']
  return scoring

def multiple_score(n_classes, y_real, y_pred):
    if n_classes > 2:
        score = {
            'test_accuracy': accuracy_score(y_real, y_pred),
            'test_balanced_accuracy': balanced_accuracy_score(y_real, y_pred),
            'test_f1': f1_score(y_real, y_pred, average='macro', zero_division=0),
            'test_precision': precision_score(y_real, y_pred, average='macro', zero_division=0),
            'test_recall': recall_score(y_real, y_pred, average='macro', zero_division=0)
        }
    else:
        score = {
            'test_accuracy': accuracy_score(y_real, y_pred),
            'test_balanced_accuracy': balanced_accuracy_score(y_real, y_pred),
            'test_f1': f1_score(y_real, y_pred, zero_division=0),
            'test_precision': precision_score(y_real, y_pred, zero_division=0),
            'test_recall': recall_score(y_real, y_pred, zero_division=0)
        }
    return score

def make_dict(n_classes, results):
    if n_classes > 2:
        score = {
            'test_accuracy': results["mean_test_accuracy"][np.nonzero(results["rank_test_accuracy"] == 1)[0][0]],
            'test_balanced_accuracy': results["mean_test_balanced_accuracy"][np.nonzero(results["rank_test_balanced_accuracy"] == 1)[0][0]],
            'test_f1': results["mean_test_f1_macro"][np.nonzero(results["rank_test_f1_macro"] == 1)[0][0]],
            'test_precision': results["mean_test_precision_macro"][np.nonzero(results["rank_test_precision_macro"] == 1)[0][0]],
            'test_recall': results["mean_test_recall_macro"][np.nonzero(results["rank_test_recall_macro"] == 1)[0][0]]
        }
    else:
        score = {
            'test_accuracy': results["mean_test_accuracy"][np.nonzero(results["rank_test_accuracy"] == 1)[0][0]],
            'test_balanced_accuracy': results["mean_test_balanced_accuracy"][np.nonzero(results["rank_test_balanced_accuracy"] == 1)[0][0]],
            'test_f1': results["mean_test_f1"][np.nonzero(results["rank_test_accuracy"] == 1)[0][0]],
            'test_precision': results["mean_test_precision"][np.nonzero(results["rank_test_precision"] == 1)[0][0]],
            'test_recall': results["mean_test_recall"][np.nonzero(results["rank_test_recall"] == 1)[0][0]]
        }
    return score

def make_dict_mean(n_classes, results):
    if n_classes > 2:
        score = {
            'test_accuracy': results["test_accuracy"].mean(),
            'test_balanced_accuracy': results["test_balanced_accuracy"].mean(),
            'test_f1': results["test_f1_macro"].mean(),
            'test_precision': results["test_precision_macro"].mean(),
            'test_recall': results["test_recall_macro"].mean()
        }
    else:
        score = {
            'test_accuracy': results["test_accuracy"].mean(),
            'test_balanced_accuracy': results["test_balanced_accuracy"].mean(),
            'test_f1': results["test_f1"].mean(),
            'test_precision': results["test_precision"].mean(),
            'test_recall': results["test_recall"].mean()
        }
    return score

def produce_NA(X, p_miss, mecha="MCAR", opt=None, p_obs=None, q=None):
    """
    Generate missing values for specifics missing-data mechanism and proportion of missing values.

    Parameters
    ----------
    X : torch.DoubleTensor or np.ndarray, shape (n, d)
        Data for which missing values will be simulated.
        If a numpy array is provided, it will be converted to a pytorch tensor.
    p_miss : float
        Proportion of missing values to generate for variables which will have missing values.
    mecha : str,
            Indicates the missing-data mechanism to be used. "MCAR" by default, "MAR", "MNAR" or "MNARsmask"
    opt: str,
         For mecha = "MNAR", it indicates how the missing-data mechanism is generated: using a logistic regression ("logistic"), quantile censorship ("quantile") or logistic regression for generating a self-masked MNAR mechanism ("selfmasked").
    p_obs : float
            If mecha = "MAR", or mecha = "MNAR" with opt = "logistic" or "quanti", proportion of variables with *no* missing values that will be used for the logistic masking model.
    q : float
        If mecha = "MNAR" and opt = "quanti", quantile level at which the cuts should occur.

    Returns
    ----------
    A dictionnary containing:
    'X_init': the initial data matrix.
    'X_incomp': the data with the generated missing values.
    'mask': a matrix indexing the generated missing values.s
    """

    to_torch = torch.is_tensor(X) ## output a pytorch tensor, or a numpy array
    if not to_torch:
        X = X.astype(np.float32)
        X = torch.from_numpy(X)

    if mecha == "MAR":
        mask = MAR_mask(X, p_miss, p_obs).double()
    elif mecha == "MNAR" and opt == "logistic":
        mask = MNAR_mask_logistic(X, p_miss, p_obs).double()
    elif mecha == "MNAR" and opt == "quantile":
        mask = MNAR_mask_quantiles(X, p_miss, q, 1-p_obs).double()
    elif mecha == "MNAR" and opt == "selfmasked":
        mask = MNAR_self_mask_logistic(X, p_miss).double()
    else:
        mask = (torch.rand(X.shape) < p_miss).double()

    X_nas = X.clone()
    X_nas[mask.bool()] = np.nan

    return {'X_init': X.double(), 'X_incomp': X_nas.double(), 'mask': mask}

def get_imputer(imp):
  if imp == 'mean':
    return SimpleImputer(strategy='mean')
  elif imp == 'median':
    return SimpleImputer(strategy='median')
  elif imp == 'KNN':
    return KNNImputer(n_neighbors=5)
  elif imp == 'iterative':
    return IterativeImputer(random_state=42)
  else:
    return SimpleImputer(strategy='mean')

def insert_missing_in_df(df,perc):
  tgt = df['target'].to_numpy()
  columns = df.columns
  X_miss = produce_NA(df.drop('target', axis=1).to_numpy(),perc,"MAR",p_obs=0.9)
  df2 = pd.DataFrame(X_miss['X_incomp'].cpu().detach().numpy(), columns = columns[:-1])
  df2['target'] = tgt
  return df2

"""# Teste Normalização"""
'''
print("Normalization")
df_norm = pd.DataFrame()
for ds in ds_list:
  print("\n TESTING ds: _", ds, "_\n")

  df = fetch_data(ds)

  for alg in target_algorithms:
    print("alg: ",alg)
    estimator = get_estimator(alg)
    # Split the data into training and test sets


    # Arrays to store scores
    cv_scores_leak = np.zeros(NUM_TRIALS)
    cv_scores_leak_all = []
    cv_scores_noleak  = np.zeros(NUM_TRIALS)
    cv_scores_noleak_all  = []
    scoring = get_scoring(df['target'].nunique())
    # Loop for each trial
    for i in range(NUM_TRIALS):
      #train_data, test_data, train_target, test_target = train_test_split(df.drop('target', axis=1), df['target'], test_size=0.2, random_state=i)
      train_data = df.drop('target', axis=1)
      train_target = df['target']
      # Create the pipeline with linear classifier step
      pipeline = Pipeline([
          ('scaler', StandardScaler()),
          ('classifier', estimator)
      ])
      cv = StratifiedKFold(n_splits=4,shuffle = True, random_state=i)

      # Evaluate the pipeline using cross-validation on the training data
      cv_scores_noleak_all.append(make_dict_mean(df['target'].nunique(),cross_validate(pipeline, train_data, train_target, cv=cv,scoring=scoring,return_train_score=False)))
      #print("CV scores (without data leakage) ",alg, " in ", ds, ": ", cv_scores_noleak[i])
      #pipeline.fit(train_data, train_target)
      cv_scores_noleak_all[i]["iteration"] = i
      cv_scores_noleak_all[i]["alg"] = alg
      cv_scores_noleak_all[i]["leak"] = False
      cv_scores_noleak_all[i]["ds"] = ds

      # Evaluate the pipeline on the test data
      #noleak_score = f1_score(pipeline.predict(test_data), test_target,average='micro')
      #print("scores test (without data leakage) ",alg, " in ", ds, ": ", noleak_score)

      # Normalize in all data

      scaler = StandardScaler()
      X = train_data.copy()
      scaler = scaler.fit(train_data)
      X = scaler.transform(X)
      train_X = pd.DataFrame(X,columns = train_data.columns)

      # Normalize the entire data
      reg = Pipeline([
          ('classifier', estimator)
      ])

      # Evaluate the pipeline using cross-validation on the entire data
      cv_scores_leak_all.append(make_dict_mean(df['target'].nunique(),cross_validate(reg, train_X, train_target, cv=cv,scoring=scoring,return_train_score=False)))
      #print("CV scores (with data leakage) ",alg, " in ", ds, ": ", cv_scores_leak[i])
      cv_scores_leak_all[i]["iteration"] = i
      cv_scores_leak_all[i]["alg"] = alg
      cv_scores_leak_all[i]["leak"] = True
      cv_scores_leak_all[i]["ds"] = ds

      cv_scores_noleak[i] = cv_scores_noleak_all[i]["test_accuracy"]
      cv_scores_leak[i] = cv_scores_leak_all[i]["test_accuracy"]
      #reg.fit(train_X, train_target)
      df_temp = pd.DataFrame([cv_scores_leak_all[i],cv_scores_noleak_all[i]])
      df_norm = pd.concat([df_norm,df_temp], ignore_index=True)
      # Normalize Data according to Leaked normalization
      #test_X = pd.DataFrame(scaler.transform(test_data),columns = train_data.columns)

      # Evaluate leaked model on test data
      #leak_score = f1_score(reg.predict(test_X),test_target,average='micro')
      #print("scores test (with data leakage) ",alg, " in ", ds, ": ", leak_score)

    print("dif in ", ds, ": ",cv_scores_noleak - cv_scores_leak )
    difference = [cv_scores_noleak - cv_scores_leak for cv_scores_noleak, cv_scores_leak in zip(cv_scores_noleak, cv_scores_leak)]

    # Create the figure and axis objects
    fig, ax1 = plt.subplots()

    # Plot the scores as lines, using the first axis
    ax1.plot(cv_scores_noleak, label='Scores no Leak in '+ ds, color='blue')
    ax1.plot(cv_scores_leak, label='Scores Leak in '+ ds, color='red')

    # Set the y-axis label for the scores
    ax1.set_ylabel('Score', color='black')
    ax1.tick_params(axis='y', labelcolor='black')

    # Create a second y-axis for the difference
    ax2 = ax1.twinx()

    # Plot the difference as a bar, using the second axis
    ax2.bar(np.arange(len(difference)), difference, alpha=0.5, color='green')

    # Set the y-axis label for the difference
    ax2.set_ylabel('Difference', color='green')
    ax2.tick_params(axis='y', labelcolor='green')

    # Add a legend to the plot
    ax1.legend()

    # Show the plot
    plt.show()

  df_norm.to_csv("norm_new.csv")
#print(difmap)
'''

"""# Teste Feature Selection"""

print("Feature Selection")

## Version 2
df_feat = pd.DataFrame()
for ds in partial_ds:
  print("\n TESTING ds: _", ds, "_\n")
  cv = StratifiedKFold(n_splits=5,shuffle = True, random_state=42 )
  df = fetch_data(ds)

  percentile_list = [1,5,10,20]
  scoring = get_scoring(df['target'].nunique())

  for alg in target_algorithms:
    print("alg: ",alg)
    for perc in percentile_list:
      print("perc: ",perc)
      estimator = get_estimator(alg)

      # Arrays to store scores
      cv_scores_leak = np.zeros(NUM_TRIALS)
      cv_scores_leak_all = []
      cv_scores_noleak  = np.zeros(NUM_TRIALS)
      cv_scores_noleak_all  = []

      X = df.drop('target', axis=1)
      y = df['target']
      leak_feature_selector = SelectPercentile(percentile = perc)
      X_leak = leak_feature_selector.fit_transform(X, y)
      if len(X_leak[0]) > 0:
        # Loop for each trial
        for i in range(NUM_TRIALS):
            train_data, test_data, train_target, test_target = train_test_split(df.drop('target', axis=1), df['target'], test_size=0.2, random_state=i)


            no_leak_feature_selector = SelectPercentile(percentile = perc)
            train_no_leak = no_leak_feature_selector.fit_transform(train_data,train_target)
            no_leak_model = estimator.fit(train_no_leak, train_target)
            test_no_leak = no_leak_feature_selector.transform(test_data)
            cv_scores_noleak_all.append(multiple_score(df['target'].nunique(),test_target,no_leak_model.predict(test_no_leak)))


            train_leak = leak_feature_selector.transform(train_data)
            leak_model = estimator.fit(train_leak, train_target)
            test_leak = leak_feature_selector.transform(test_data)
            cv_scores_leak_all.append(multiple_score(df['target'].nunique(),test_target,leak_model.predict(test_leak)))

            cv_scores_noleak[i] = cv_scores_noleak_all[i]["test_accuracy"]
            cv_scores_leak[i] = cv_scores_leak_all[i]["test_accuracy"]

            cv_scores_leak_all[i]["ds"] = ds
            cv_scores_leak_all[i]["iteration"] = i
            cv_scores_leak_all[i]["alg"] = alg
            cv_scores_leak_all[i]["leak"] = True
            cv_scores_leak_all[i]["perc"] = perc

            cv_scores_noleak_all[i]["ds"] = ds
            cv_scores_noleak_all[i]["iteration"] = i
            cv_scores_noleak_all[i]["alg"] = alg
            cv_scores_noleak_all[i]["leak"] = False
            cv_scores_noleak_all[i]["perc"] = perc

            df_temp = pd.DataFrame([cv_scores_leak_all[i],cv_scores_noleak_all[i]])
            df_feat = pd.concat([df_feat,df_temp], ignore_index=True)
            print("CV scores (with data leakage) ",alg, " in ", ds, ": ", cv_scores_leak[i])
            print("CV scores (without data leakage) ",alg, " in ", ds, ": ", cv_scores_noleak[i])
  df_feat.to_csv("feat.csv")


'''
      difference = [cv_scores_noleak - cv_scores_leak for cv_scores_noleak, cv_scores_leak in zip(cv_scores_noleak, cv_scores_leak)]
      # Create the figure and axis objects
      fig, ax1 = plt.subplots()

      # Plot the scores as lines, using the first axis
      ax1.plot(cv_scores_noleak, label='Scores no Leak in '+ ds, color='blue')
      ax1.plot(cv_scores_leak, label='Scores Leak in '+ ds, color='red')

      # Set the y-axis label for the scores
      ax1.set_ylabel('Score', color='black')
      ax1.tick_params(axis='y', labelcolor='black')

      # Create a second y-axis for the difference
      ax2 = ax1.twinx()

      # Plot the difference as a bar, using the second axis
      ax2.bar(np.arange(len(difference)), difference, alpha=0.5, color='green')

      # Set the y-axis label for the difference
      ax2.set_ylabel('Difference', color='green')
      ax2.tick_params(axis='y', labelcolor='green')

      # Add a legend to the plot
      ax1.legend()

      # Show the plot
      plt.show()



"""# Teste HiperParameter Tunning

"""

df_hyp = pd.DataFrame()


                      "KNN": {
                          'n_neighbors': [3, 5, 7, 9, 11],
                          'weights': ['uniform', 'distance'],
                          'metric': ['euclidean', 'manhattan']},
                      "SVC": {
                          'C': [0.1, 1, 10, 100],
                          'kernel': ['linear', 'rbf', 'poly'],
                          'gamma': ['scale', 'auto']},
                      "LR": {
                          'penalty': ['l1', 'l2', 'elasticnet'],
                          'C': [0.01, 0.1, 1, 10, 100],
                          'solver': ['liblinear', 'saga', 'lbfgs', 'newton-cg'],
                          'max_iter': [100, 500, 1000],
                          'class_weight': [None, 'balanced']},
                      "NB": {
                          'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6, 1e-5]},
                      "DT": {
                          'criterion': ['gini', 'entropy'],
                          'max_depth': [3, 5, 10, 20, None],
                          'min_samples_split': [2, 5, 10],
                          'min_samples_leaf': [1, 2, 4],
                          'max_leaf_nodes': [None, 5, 10, 20]},
                      "RF": {
                          'n_estimators': [100, 200, 500],
                          'criterion': ['gini', 'entropy'],
                          #'max_depth': [3, 5, 10, 20, None],

                          'min_samples_split': [2, 5, 10],
                          #'min_samples_leaf': [1, 2, 4],
                          #'max_leaf_nodes': [None, 5, 10, 20],
                          #'bootstrap': [True, False]},
                      }



hyperparameterDict = { "KNN": {
                          'n_neighbors': [3, 5, 7, 9, 11],
                          'metric': ['euclidean', 'manhattan']},
                      "SVC": {
                          'C': [0.01, 0.1, 1, 10, 100],
                          'kernel': ['linear', 'rbf', 'poly'],
                      "LR": {
                          'penalty': ['l1', 'l2', 'elasticnet'],
                          'C': [0.01, 0.1, 1, 10, 100],
                      "NB": {
                          'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6, 1e-5]},
                      "DT": {
                          'max_depth': [3, 5, 8, 10, None],
                      "RF": {
                          'n_estimators': [100, 200, 500],
                         'max_depth': [3, 5, 8, 10, None],
                      }
}
'''
hyperparameterDict = { "KNN": {
                          'n_neighbors': [3, 5, 7, 9, 11],
                          'metric': ['euclidean', 'manhattan']},
                      "SVC": {
                          'C': [0.01, 0.1, 1, 10, 100],
                          'kernel': ['linear', 'rbf', 'poly'],},
                      "LR": {
                          'solver': [ 'saga', 'lbfgs'],
                          'C': [0.01, 0.1, 1, 10, 100],},
                      "NB": {
                          'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6, 1e-5]},
                      "DT": {
                          'max_depth': [3, 5, 8, 10, None],},
                      "RF": {
                          'n_estimators': [100, 200, 500],
                          'max_depth': [3, 5, 8, 10, None],},
                      "NN": {  # Neural Network entry
                          'hidden_layer_sizes': [(50,), (100,), (100, 50), (100, 100)],
                          'activation': ['relu', 'tanh', 'logistic'],
                          'solver': ['adam', 'sgd'],
                          'alpha': [0.0001, 0.001, 0.01],
                          'learning_rate': ['constant', 'adaptive'],
                          'max_iter': [1000, 1500], 
                          'learning_rate_init': [0.001, 0.0001] 
                        }
}
df_hyp = pd.DataFrame()

target_columns_clf = []
target_columns = []

print("HiperParameter")
for ds in ds_list:
  print("\n TESTING ds: _", ds, "_\n")
  cv = StratifiedKFold(n_splits=5,shuffle = True, random_state=42 )
  df = fetch_data(ds)
  scoring = get_scoring(df['target'].nunique())
  for alg in target_algorithms:
    print("alg: ",alg)
    estimator = get_estimator(alg)

    # Arrays to store scores
    cv_scores_leak = np.zeros(NUM_TRIALS)
    cv_scores_leak_all = []
    cv_scores_noleak  = np.zeros(NUM_TRIALS)
    cv_scores_noleak_all  = []

    p_grid = hyperparameterDict[alg]
    # Loop for each trial
    for i in range(NUM_TRIALS):
        #train_data, test_data, train_target, test_target = train_test_split(df.drop('target', axis=1), df['target'], test_size=0.2, random_state=i)
        train_data = df.drop('target', axis=1)
        train_target = df['target']
        # Choose cross-validation techniques for the inner and outer loops,
        # independently of the dataset.
        # E.g "GroupKFold", "LeaveOneOut", "LeaveOneGroupOut", etc.
        inner_cv = StratifiedKFold(n_splits=4, shuffle=True, random_state=i)
        outer_cv = StratifiedKFold(n_splits=4, shuffle=True, random_state=i)

        # Non_nested parameter search and scoring
        clf = GridSearchCV(estimator=estimator, param_grid=p_grid, cv=outer_cv,scoring=scoring,refit='accuracy')
        clf.fit(train_data,train_target)
        clf_results = make_dict(df['target'].nunique(),clf.cv_results_)
        cv_scores_leak_all.append(clf_results)

        #print("CV scores (with data leakage) ",alg, " in ", ds, ": ", cv_scores_leak[i])


        # Nested CV with parameter optimization
        clf = GridSearchCV(estimator=estimator, param_grid=p_grid, cv=inner_cv,refit='accuracy')
        nested_score = cross_validate(clf, X=train_data, y=train_target, cv=outer_cv,scoring=scoring)
        cv_scores_noleak_all.append(make_dict_mean(df['target'].nunique(),nested_score))
        #print("CV scores (without data leakage) ",alg, " in ", ds, ": ", cv_scores_noleak[i])

        cv_scores_noleak[i] = cv_scores_noleak_all[i]["test_accuracy"]
        cv_scores_leak[i] = cv_scores_leak_all[i]["test_accuracy"]

        cv_scores_leak_all[i]["ds"] = ds
        cv_scores_leak_all[i]["iteration"] = i
        cv_scores_leak_all[i]["alg"] = alg
        cv_scores_leak_all[i]["leak"] = True

        cv_scores_noleak_all[i]["ds"] = ds
        cv_scores_noleak_all[i]["iteration"] = i
        cv_scores_noleak_all[i]["alg"] = alg
        cv_scores_noleak_all[i]["leak"] = False

        df_temp = pd.DataFrame([cv_scores_leak_all[i],cv_scores_noleak_all[i]])
        df_hyp = pd.concat([df_hyp,df_temp], ignore_index=True)
        print("CV scores (with data leakage) ",alg, " in ", ds, ": ", cv_scores_leak[i])
        print("CV scores (without data leakage) ",alg, " in ", ds, ": ", cv_scores_noleak[i])

    '''
    difference = [cv_scores_noleak - cv_scores_leak for cv_scores_noleak, cv_scores_leak in zip(cv_scores_noleak, cv_scores_leak)]

    # Create the figure and axis objects
    fig, ax1 = plt.subplots()

    # Plot the scores as lines, using the first axis
    ax1.plot(cv_scores_noleak, label='Scores no Leak in '+ ds, color='blue')
    ax1.plot(cv_scores_leak, label='Scores Leak in '+ ds, color='red')

    # Set the y-axis label for the scores
    ax1.set_ylabel('Score', color='black')
    ax1.tick_params(axis='y', labelcolor='black')

    # Create a second y-axis for the difference
    ax2 = ax1.twinx()

    # Plot the difference as a bar, using the second axis
    ax2.bar(np.arange(len(difference)), difference, alpha=0.5, color='green')

    # Set the y-axis label for the difference
    ax2.set_ylabel('Difference', color='green')
    ax2.tick_params(axis='y', labelcolor='green')

    # Add a legend to the plot
    ax1.legend()

    # Show the plot
    plt.show()
    '''
  df_hyp.to_csv("hyp.csv")

"""#Teste Value Imputation"""
'''
print("Value Impute")
df_impute = pd.DataFrame()
perc_miss = [0.05,0.1,0.2,0.3]
imp_list = ['mean','median','KNN']#,'iterative']
for ds in ds_list:
  print("\n TESTING ds: _", ds, "_\n")
  for p in perc_miss:
    print("p miss: ",p)
    cv = StratifiedKFold(n_splits=5,shuffle = True, random_state=42 )
    df = insert_missing_in_df(fetch_data(ds),p)
    scoring = get_scoring(df['target'].nunique())
    for alg in target_algorithms:
      print("alg: ",alg)

      estimator = get_estimator(alg)
      for imp in imp_list:
        imputer = get_imputer(imp)
        # Arrays to store scores
        cv_scores_leak = np.zeros(NUM_TRIALS)
        cv_scores_leak_all = []
        cv_scores_noleak  = np.zeros(NUM_TRIALS)
        cv_scores_noleak_all  = []
        # Loop for each trial
        for i in range(NUM_TRIALS):

          train_data = df.drop('target', axis=1)
          train_target = df['target']
          # Create the pipeline with linear classifier step
          pipeline = Pipeline([
              ('imputer', imputer),
              ('scaler', StandardScaler()),
              ('classifier', estimator)
          ])
          cv = StratifiedKFold(n_splits=4,shuffle = True, random_state=i)

          # Evaluate the pipeline using cross-validation on the training data
          cv_scores_noleak_all.append(make_dict_mean(df['target'].nunique(),cross_validate(pipeline, train_data, train_target, cv=cv,scoring=scoring,return_train_score=False)))


          # imput using all data

          X = train_data.copy()
          impt_2 = imputer.fit(train_data)
          X = impt_2.transform(X)
          train_X = pd.DataFrame(X,columns = train_data.columns)

          # Normalize the entire data
          reg = Pipeline([
              ('scaler', StandardScaler()),
              ('classifier', estimator)
          ])

          # Evaluate the pipeline using cross-validation on the entire data
          cv_scores_leak_all.append(make_dict_mean(df['target'].nunique(),cross_validate(reg, train_X, train_target, cv=cv,scoring=scoring,return_train_score=False)))

          cv_scores_noleak[i] = cv_scores_noleak_all[i]["test_accuracy"]
          cv_scores_leak[i] = cv_scores_leak_all[i]["test_accuracy"]

          cv_scores_leak_all[i]["ds"] = ds
          cv_scores_leak_all[i]["iteration"] = i
          cv_scores_leak_all[i]["alg"] = alg
          cv_scores_leak_all[i]["leak"] = True
          cv_scores_leak_all[i]["imputer"] = imp
          cv_scores_leak_all[i]["perc-miss"] = p

          cv_scores_noleak_all[i]["ds"] = ds
          cv_scores_noleak_all[i]["iteration"] = i
          cv_scores_noleak_all[i]["alg"] = alg
          cv_scores_noleak_all[i]["leak"] = False
          cv_scores_noleak_all[i]["imputer"] = imp
          cv_scores_noleak_all[i]["perc-miss"] = p

          df_temp = pd.DataFrame([cv_scores_leak_all[i],cv_scores_noleak_all[i]])
          df_impute  = pd.concat([df_impute ,df_temp], ignore_index=True)

      difference = [cv_scores_noleak - cv_scores_leak for cv_scores_noleak, cv_scores_leak in zip(cv_scores_noleak, cv_scores_leak)]
      # Create the figure and axis objects
      fig, ax1 = plt.subplots()

      # Plot the scores as lines, using the first axis
      ax1.plot(cv_scores_noleak, label='Scores no Leak in '+ ds, color='blue')
      ax1.plot(cv_scores_leak, label='Scores Leak in '+ ds, color='red')

      # Set the y-axis label for the scores
      ax1.set_ylabel('Score', color='black')
      ax1.tick_params(axis='y', labelcolor='black')

      # Create a second y-axis for the difference
      ax2 = ax1.twinx()

      # Plot the difference as a bar, using the second axis
      ax2.bar(np.arange(len(difference)), difference, alpha=0.5, color='green')

      # Set the y-axis label for the difference
      ax2.set_ylabel('Difference', color='green')
      ax2.tick_params(axis='y', labelcolor='green')

      # Add a legend to the plot
      ax1.legend()

      # Show the plot
      plt.show()

  df_impute.to_csv("impute.csv")
'''
